### ISSUE TITLE
AppSync の GraphQL エンドポイントを作成する

### ISSUE THREAD

**Issue by matsuihidetoshi** [jaws-ug/jpk2024-broadcast-viewer#2]
# 概要
https://github.com/jaws-ug/jpk2024-broadcast-backend の Lambda 関数からも mutation できるような形で、 GraphQL のエンドポイントを作成する。
したがって、 Cognito の認証というより IAM 認証の形にしたい

# tasks
- [ ] `amplify add api` 的なやつをやる
- [ ] その時に Cognito じゃない IAM のやつを選択する
- [ ] https://github.com/jaws-ug/jpk2024-broadcast-backend との繋ぎ込みができる形にする

**Comment by Yoshiitaka** [comment]
これは一旦なしでLambdaをバックエンドとして活用する認識。
